# Generated by Django 3.1.2 on 2020-10-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='score',
        ),
    ]
