# Generated by Django 3.1.2 on 2020-10-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_rate_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rate',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='rate',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rate',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('make', 'model')},
        ),
    ]
