# Generated by Django 3.1.2 on 2020-10-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201022_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rate',
            name='make',
        ),
    ]
