# Generated by Django 3.1.2 on 2020-10-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201023_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
    ]
